export const GET_RECOMENDATIONS = "GET_RECOMENDATIONS";
export const GET_RECOMENDATIONS_LOADING = "GET_RECOMENDATIONS_LOADING";
export const CONTINUE_READING = "CONTINUE_READING";
export const CONTINUE_READING_LOADING = "CONTINUE_READING_LOADING";
export const VIDEOS_BY_TOPIC_ID = "VIDEO_BY_TOPIC_ID";

export const VIDEOS_BY_TOPIC_ID_LOADING = "VIDEO_BY_TOPIC_ID_LOADING";

export const TOGGLE_ALERT = "TOGGLE_ALERT";

export const AUTH_LOADING = "AUTH_LOADING";

export const AUTHENTICATED = "AUTHENTICATED";

export const GET_TOPICS_LOADING = "GET_TOPICS_LOADING";
export const GET_TOPICS = "GET_TOPICS";

export const GET_SUBJECTS_LOADING = "GET_SUBJECTS_LOADING";
export const GET_SUBJECTS = "GET_SUBJECTS";

export const SUBJECT_LOADING = "SUBJECT_LOADING";
export const LOAD_SELECTED_SUBJECT = "LOAD_SELECTED_SUBJECT";

export const SELECTED_VIDEO = "SELECTED_VIDEO";

export const FAQ_LOADING = "FAQ_LOADING";
export const LOAD_FAQ_DATA = "LOAD_FAQ_DATA";

export const GET_SUBSCRIPTION_PLANS = "GET_SUBSCRIPTION_PLANS";
export const SUBSCRIPTION_LOADING = "SUBSCRIPTION_LOADING";

export const GET_COUPONS = "GET_COUPONS";
export const ADD_FREE_TRAIL = "ADD_FREE_TRAIL";

export const GET_ORDER_ID = "GET_ORDER_ID";
export const GET_TRANSCATION_ID = "GET_TRANSCATION_ID";
export const UNAUTHENTICATED = "UNAUTHENTICATED";

export const LOAD_SELECTED_VIDEO = "LOAD_SELECTED_VIDEO";
export const SELECT_VIDEO_INDEX = "SELECT_VIDEO_INDEX";

export const VIDEO_DETAILS_BY_ID_LOADING = "VIDEO_DETAILS_BY_ID_LOADING";

export const VIDEO_DETAILS_BY_ID = "VIDEO_DETAILS_BY_ID";

export const LOAD_SEARCH_DATA = "LOAD_SEARCH_DATA";
export const SEARCH_DATA_LOADING = "SEARCH_DATA_LOADING";

export const SET_SCREEN_WIDTH = "SET_SCREEN_WIDTH";

/////////////////////////////////////////////

export const GET_COLLEGE_DATA = "GET_COLLEGE_DATA";
export const GET_HOMESCREEN_DATA = "GET_HOMESCREEN_DATA";
export const SUBMIT_FEEDBACK = "SUBMIT_FEEDBACK";

export const LOAD_SELECTED_CLASS = "LOAD_SELECTED_CLASS";
export const CLASS_LOADING = "CLASS_LOADING";
export const LOAD_CLASSES = "LOAD_CLASSES";

export const LOAD_SUBJECTS = "LOAD_SUBJECTS";

export const LOAD_SELECT_CONTENT = "LOAD_SELECT_CONTENT";
export const LOAD_BOOKMARK_SUBJECT = "LOAD_BOOKMARK_SUBJECT";

export const TOPIC_LOADING = "TOPIC_LOADING";
export const LOAD_TOPICS = "LOAD_TOPICS";
export const LOAD_SELECTED_TOPIC = "LOAD_SELECTED_TOPIC";
export const LOAD_SELECTED_CONTENT_TYPE = "LOAD_SELECTED_CONTENT_TYPE";

export const LOAD_SEARCH_SHOW = "LOAD_SEARCH_SHOW";

export const QUESTION_LOADING = "QUESTION_LOADING";
export const LOAD_QUESTION = "LOAD_QUESTION";
export const LOAD_FILTERED_QUESTION = "LOAD_FILTERED_QUESTION";
export const LOAD_SELECTED_QUESTION = "LOAD_SELECTED_QUESTION";
export const LOAD_SELECTED_QUESTION_BY_API = "LOAD_SELECTED_QUESTION_BY_API";
export const LOAD_UPDATED_QUESTION = "LOAD_UPDATED_QUESTION";
export const LOAD_BOOKMARKED_QNA = "LOAD_BOOKMARKED_QNA";

export const KEY_LOADING = "KEY_LOADING";
export const LOAD_KEY = "LOAD_KEY";
export const SEARCH_KEY_LOADING = "SEARCH_KEY_LOADING";
export const LOAD_FILTERED_KEY = "LOAD_FILTERED_KEY";
export const LOAD_SELECTED_KEY = "LOAD_SELECTED_KEY";
export const LOAD_SELECTED_KEY_BY_API = "LOAD_SELECTED_KEY_BY_API";
export const LOAD_BOOKMARKED_KEY = "LOAD_BOOKMARKED_KEY";
export const LOAD_UPDATED_KEY = "LOAD_UPDATED_KEY";
export const LOAD_CONTENT_KEY = "LOAD_CONTENT_KEY";

export const TEST_LOADING = "TEST_LOADING";
export const LOAD_QBANK_TEST = "LOAD_QBANK_TEST";
export const LOAD_TEST = "LOAD_TEST";
export const LOAD_TEST_MODE = "LOAD_TEST_MODE";
export const LOAD_MOCK_TEST = "LOAD_MOCK_TEST";
export const LOAD_SCORE = "LOAD_SCORE";
export const MCQ_LOADING = "MCQ_LOADING";
export const LOAD_MCQ = "LOAD_MCQ";
export const PAGINATION = "PAGINATION";
export const LOAD_LANDING_MCQ = "LOAD_ALL_MCQ";
export const LOAD_FILTERED_MCQ = "LOAD_FILTERED_MCQ";
export const LOAD_SUB_FILTERED_MCQ = "LOAD_SUB_FILTERED_MCQ";
export const LOAD_SELECTED_MCQ = "LOAD_SELECTED_MCQ";
export const LOAD_SELECTED_MCQ_BY_API = "LOAD_SELECTED_MCQ_BY_API";
export const LOAD_UPDATED_MCQ = "LOAD_UPDATED_MCQ";
export const LOAD_BOOKMARKED_MCQ = "LOAD_BOOKMARKED_MCQ";
export const LOAD_FILTERED_MOCK_TEST = "LOAD_FILTERED_MOCK_TEST";
export const LOAD_MOCK_TEST_SCORE = "LOAD_MOCK_TEST_SCORE";
export const MOCK_SCORE_LOADING = "MOCK_SCORE_LOADING";
export const LOAD_REVISION_DATE = "LOAD_REVISION_DATE";
export const LOAD_FILTERED_REVISION_DATE = "LOAD_FILTERED_REVISION_DATE";
export const LOAD_REVISION_TEST_MODE = "LOAD_REVISION_TEST_MODE";
export const LOAD_VIEW_EXPLANATION = "LOAD_VIEW_EXPLANATION";
export const LOAD_VIEW_MOCK = "LOAD_VIEW_MOCK";
export const LOAD_CONTENT_MCQ = "LOAD_CONTENT_MCQ";
export const SET_SELECTED_OPTION_MARKET_MCQS =
  "SET_SELECTED_OPTION_MARKET_MCQS";
export const REVISION_LOADING = "REVISION_LOADING";
export const REVISION_STATUS = "REVISION_STATUS";

export const COLLEGE_LOADING = "COLLEGE_LOADING";
export const ALL_COLLEGE_DATA = "ALL_COLLEGE_DATA";
export const LOAD_COLLEGE_DATA = "LOAD_COLLEGE_DATA";
export const STATE_COLLEGE_DATA = "STATE_COLLEGE_DATA";
export const STATE_DATA_LOADING = "STATE_DATA_LOADING";
export const LOAD_STATE_DATA = "LOAD_STATE_DATA";
export const LOAD_CITIES_DATA = "LOAD_CITIES_DATA";
export const LOAD_FINDER_DATA = "LOAD_FINDER_DATA";
export const STATE_SELECTED = "STATE_SELECTED";
export const ALL_STATE_COLLEGE_DATA = "ALL_STATE_COLLEGE_DATA";

export const COMMENT_LOADING = "COMMENT_LOADING";
export const ALL_COMMENT_DATA = "ALL_COMMENT_DATA";
export const POST_COMMENT_DATA = "POST_COMMENT_DATA";
export const AUTH_COMMENT_DATA = "AUTH_COMMENT_DATA";

export const LOAD_RECOMMENDED_DATA = "LOAD_RECOMMENDED_DATA";
export const EXPLORE_LOADING = "EXPLORE_LOADING";
export const TOPICS_STATUS = "TOPICS_STATUS";
export const MCQS_STATUS = "MCQS_STATUS";
export const SELECTED_EXPLORE_SECTION = "SELECTED_EXPLORE_SECTION";

export const GET_STARTED_TOPIC = "GET_STARTED_TOPIC";

export const BOOKMARK_UNSELECT_TOPIC = "BOOKMARK_UNSELECT_TOPIC";
export const GET_TOPIC_DESCRIPTION = "GET_TOPIC_DESCRIPTION";
export const TOPIC_DESCRIPTION_LOADING = "TOPIC_DESCRIPTION_LOADING";
export const LOAD_ALL_KEY = "LOAD_ALL_KEY";
export const TOPIC_WISE_DATA = "TOPIC_WISE_DATA";
export const TOPIC_WISE_LOADING = "TOPIC_WISE_LOADING";
export const SELECTED_CONCEPT = "SELECTED_CONCEPT";
export const SELECTED_CONCEPT_LOADING = "SELECTED_CONCEPT_LOADING";
export const SELECTED_CONCEPT_KEY = "SELECTED_CONCEPT_KEY";
export const SELECTED_CONCEPT_MCQ = "SELECTED_CONCEPT_MCQ";
export const SELECTED_SEARCH_TOPIC = "SELECTED_SEARCH_TOPIC";
export const GET_CONCEPTS_DATA = "GET_CONCEPTS_DATA";
export const CONCEPTS_LOADING = "CONCEPTS_LOADING";

export const GET_TEST_LIST = "GET_TEST_LIST";
export const GET_CUSTOM_TEST_SCORE = "GET_CUSTOM_TEST_SCORE";
export const TEST_HOME_STATUS = "TEST_HOME_STATUS";
export const TEST_SUBJECT_STATUS = "TEST_SUBJECT_STATUS";
export const TEST_TOPIC_STATUS = "TEST_TOPIC_STATUS";
export const TEST_HASTAG_STATUS = "TEST_HASTAG_STATUS";
export const TEST_OVERVIEW_STATUS = "TEST_OVERVIEW_STATUS";
export const GET_HASTAG_LIST = "GET_HASTAG_LIST";
export const GET_SUBJECT_BUTTON_STATUS = "GET_SUBJECT_BUTTON_STATUS";
export const GET_CUSTOM_TEST_DATA = "GET_CUSTOM_TEST_DATA";
export const LOAD_SUBJECT_ID_LIST = "LOAD_SUBJECT_ID_LIST";
export const TOPIC_CHECK_STATUS = "TOPIC_CHECK_STATUS";
export const CUSTOM_SELECTED_CLASS = "CUSTOM_SELECTED_CLASS";
export const LOAD_BOOKMARK_TOPICS = "LOAD_BOOKMARK_TOPICS";
export const UPDATE_TOPIC_ID_LIST = "UPDATE_TOPIC_ID_LIST";
export const UPDATE_TOPICS_TOTAL_DATA = "UPDATE_TOPICS_TOTAL_DATA";
export const CURRENT_STEP = "CURRENT_STEP";
export const COMPLETED_STEP = "COMPLETED_STEP";
export const SELECTED_HASTAG_LIST = "SELECTED_HASTAG_LIST";
export const ADD_NUMBER = "ADD_NUMBER";
export const ADD_TEST_NAME = "ADD_TEST_NAME";
export const CREATE_CUSTOM_TEST = "CREATE_CUSTOM_TEST";
export const GET_MCQ_DATA = "GET_MCQ_DATA";
export const SUBJECT_ACTIVE = "SUBJECT_ACTIVE";
export const GET_PREVIOUS = "GET_PREVIOUS";
export const CUSTOM_TEST_LOADING = "CUSTOM_TEST_LOADING";
export const GET_TOPIC_LIST = "GET_TOPIC_LIST";
// export const GET_INITIAL_SUBJECT_LIST = "GET_INITIAL_SUBJECT_LIST";
export const CLEAR_ALL = "CLEAR_ALL";
export const TEST_REVIEW_LOADING = "TEST_REVIEW_LOADING";

// lesson types
export const SELECTED_LESSON = "SELECTED_LESSON";
export const MILESTONE_DATA = "MILESTONE_DATA";
export const MILESTONE_DATA_LOADING = "MILESTONE_DATA_LOADING";
export const NEXT_CONTENT_STATUS = "NEXT_CONTENT_STATUS";
export const UPDATE_MILESTONE_DATA = "UPDATE_MILESTONE_DATA";
export const CURRENT_MILESTONE_INDEX = "CURRENT_MILESTONE_INDEX";
export const MILESTONE_RESULT = "MILESTONE_RESULT";
export const MILESTONE_RESULT_LOADING = "MILESTONE_RESULT_LOADING";
export const LOAD_CONTENT_DATA = "LOAD_CONTENT_DATA";
export const GET_LESSON_SCORE = "GET_LESSON_SCORE";
export const LOADING_SCORE = "LOADING_SCORE";

export const GET_ACTIVE_LESSON = "GET_ACTIVE_LESSON";
export const SYNC_DATA_LOADING = "SYNC_DATA_LOADING";
export const OPEN_LESSONS_SECTION = "OPEN_LESSONS_SECTION";

export const PAUSE_MILESTONE = "PAUSE_MILESTONE";
export const GET_MILESTONE_STATUS = "GET_MILESTONE_STATUS";
export const LESSON_MODAL_STATUS = "LESSON_MODAL_STATUS";
export const LESSON_MODE = "LESSON_MODE";
export const REVIEW_MILESTONE_INDEX = "REVIEW_MILESTONE_INDEX";
export const LESSON_LOADING = "LESSON_LOADING";
export const LOAD_LESSONS_DATA = "LAOD_LESSONS_DATA";
export const NEXT_MILESTONE_LOADING = "NEXT_MILESTONE_LOADING";
export const LOAD_SELECTED_FILLUP_BY_API = "LOAD_SELECTED_FILLUP_BY_API";
export const LOAD_SELECTED_ATF_BY_API = "LOAD_SELECTED_ATF_BY_API";
export const LOAD_SELECTED_MCCQ_BY_API = "LOAD_SELECTED_MCCQ_BY_API";

// videos
export const LOAD_VIDEOS_DATA = "LOAD_VIDEOS_DATA";
export const VIDEOS_LOADING = "VIDEOS_LOADING";

//Continue learning
export const LOAD_CONTINUE_LEARNING_DATA = "LOAD_CONTINUE_LEARNING_DATA";
export const CONTINUE_LEARNING_LOADING = "CONTINUE_LEARNING_LOADING";

// Rating
export const SHOW_RATING_CARD = "SHOW_RATING_CARD";
export const RATING_TITLES = "RATING_TITLES";
